---
ID: "e74753c8-76e8-4b2a-aa9b-839636b47173"
Parent: "d58a65ec-22e1-414c-838c-2c46c713adbb"
Template: "d58a65ec-22e1-414c-838c-2c46c713adbb"
Path: /sitecore/templates/Feature/Catalyst/HeroBanner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250519T141456Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\miguel.minoldo@valtech.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\miguel.minoldo@valtech.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b3a2dd7c-7def-42a6-b608-86fc25a7b2eb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\miguel.minoldo@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250519T141456Z
