
    // GENERATED BY build-tokens.js
    import React, { JSX } from 'react';
    import dynamic from "next/dynamic";

    export type ThemeProviderProps = {
      site?: string;
    };

    const themes : any = {
      
base: dynamic(() => import('./sites/base')),
corp: dynamic(() => import('./sites/corp')),
net: dynamic(() => import('./sites/net'))
    };

    export const ThemeProvider = ({ site = "Blueprint" }: ThemeProviderProps): JSX.Element => {
      const Theme = themes[site];
      return <Theme />;
    };
  