---
ID: "ed7be225-c22a-4fd1-86f2-e97ba3f32f8f"
Parent: "d0a87b63-e4bf-4fef-928b-409ae56f40bb"
Template: "c9afbddc-954b-4404-9a88-12e3dedba816"
Path: /sitecore/system/Settings/Foundation/Catalyst/Theming/base
SharedFields:
- ID: "6f515e21-7f5c-45b7-b68d-d2554f3328b7"
  Hint: ThemeName
  Value: base
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220825T193755Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "cc540a32-c485-4e88-a202-f2bf5c5a3ee3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\miguel.minoldo@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221221T125805Z
