---
ID: "7ead5861-f204-454b-b2a4-95fc918d2079"
Parent: "197c5ea5-15cf-48d6-a7a9-70fee9d9c452"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: /sitecore/templates/Branches/Project/Catalyst/Scaffolding/Catalyst Blueprint Site/$name/Settings/Shared Sites Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221115T130843Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Anonymous
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "676364e2-26c7-481e-80f3-b1b6d63b853c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Anonymous
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221115T130843Z
