---
ID: "097276d0-aceb-416a-8731-00bcddbfcbc9"
Parent: "197c5ea5-15cf-48d6-a7a9-70fee9d9c452"
Template: "f5a83a0e-5eab-441d-83a6-1357e4c8d03b"
Path: /sitecore/templates/Branches/Project/Catalyst/Scaffolding/Catalyst Blueprint Site/$name/Settings/Theme Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220825T204310Z
    - ID: "2abe864b-e7de-4494-b7d1-7bfe529bf007"
      Hint: Theme
      Value: "{2A642758-DD4C-4B35-A9D4-2BBC40C1E53C}"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bc641624-ba8b-499e-ae46-ccbf19b3f48f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\miguel.minoldo@valtech.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20221207T083022Z
- Language: "en-US"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220825T234450Z
    - ID: "2abe864b-e7de-4494-b7d1-7bfe529bf007"
      Hint: Theme
      Value: "{2A642758-DD4C-4B35-A9D4-2BBC40C1E53C}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "53cac46d-acc8-4a26-bd5d-fe758413d6a0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220825T234453Z
