---
ID: "2fc12b0b-21ee-4461-bd09-042334056405"
Parent: "f5a83a0e-5eab-441d-83a6-1357e4c8d03b"
Template: "f5a83a0e-5eab-441d-83a6-1357e4c8d03b"
Path: /sitecore/templates/Foundation/Catalyst/Theming/ThemeSettings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220825T204148Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5ec4d11a-403b-4a82-8a8a-334fe2a4328d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220825T204148Z
